name: tests

on: [push, pull_request]

jobs:
  macos:
    name: Mac
    runs-on: macOS-latest
    strategy:
      matrix:
        config: [debug, release]
        include:
        - config: release
          args:  -Xswiftc -enable-testing
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -v -c ${{ matrix.config }}
    - name: Test (macOS)
      run: swift test -v -c ${{ matrix.config }} ${{ matrix.args }}
    - name: Test (iOS)
      run: xcodebuild clean test -workspace . -scheme BindingsExtensions -destination "name=iPad Pro (11-inch)"
    - name: Slack Notification
      uses: elegantchaos/slatify@master
      with:
          type: ${{ job.status }}
          job_name: 'Mac Tests (${{ matrix.config }})'
          mention_if: 'failure'
          url: ${{ secrets.SLACK_WEBHOOK }}
